#!/bin/zsh

# Set up Node Version Manager
source /usr/share/nvm/init-nvm.sh
export NVM_DIR="$HOME/.nvm"                            # You can change this if you want.
export NVM_SOURCE="/usr/share/nvm"                     # The AUR package installs it to here.
. "$NVM_SOURCE/nvm.sh"  # Load NVM
