#!/bin/zsh

local TARGETDIR="files/$(date +%s)"
local FOLDERDIR="/usr/share/wordpress/$TARGETDIR"

ssh-add ~/.ssh/id_ed25519_digital

ssh gentz@gentz.rocks "mkdir -p $FOLDERDIR" || exit $?

for FILE in "$@"; do
    scp -r "$FILE" "gentz@gentz.rocks:$FOLDERDIR" || exit $?
done

for FILE in "$@"; do
    echo "https://gentz.rocks/$TARGETDIR/$(basename "$FILE")"
done
