#!/bin/zsh

LOCKDIR="$HOME/utils/beep_internals/rlock"

function cleanup {
    if ! rm -rf "$LOCKDIR"; then
        echo "beeper: Failed to remove lock directory '$LOCKDIR'"
    fi
}

while ! mkdir "$LOCKDIR" >/dev/null 2>&1; do
    mkdir "$LOCKDIR"/next >/dev/null 2>&1
done

trap "cleanup" EXIT
~/utils/beep_internals/songs/"$(ls ~/utils/beep_internals/songs | shuf -n1)"
